<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Page_Help_option</name>
   <tag></tag>
   <elementGuidId>e37f7187-d069-4646-8d1c-4ecbe89d9998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-object-id</name>
      <type>Main</type>
      <value>pageHelp</value>
   </webElementProperties>
</WebElementEntity>
