<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ploicy_tab</name>
   <tag></tag>
   <elementGuidId>0ffcb48b-90ab-41a8-a8a4-c790bbbafe91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>POLICY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-object-id</name>
      <type>Main</type>
      <value>FPTopLevelNavBarItem_POLICY</value>
   </webElementProperties>
</WebElementEntity>
