<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Profile_Icon</name>
   <tag></tag>
   <elementGuidId>692f9007-1232-4bdf-8cdc-070385cd06f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-object-id</name>
      <type>Main</type>
      <value>profileIcon</value>
   </webElementProperties>
</WebElementEntity>
